### PR TITLE
Interface with all tools present and other major and minor code changes.

### PR DESCRIPTION
**Pull request by catherinegua**
Updated a bunch of the functions, and now users can load an interface with all the tools in one place that they can select from.

### CODE REVIEW

**Comment by jessiwitti** [comment]
I needed to load library(shiny) manually in order to make the shiny app work, but then it looked really nice. I like the quotes! However, when I click on pause or play the shiny app just breaks down. 
 
 In your name space I only see your three previous functions without the shiny or the quotes function.

In R I couldn't see a help page, but I see in your man file that you have some sort of documentation.

**Comment by jessiwitti** [comment]
Oh and I cannot find your outline for the report!

(Maybe we didn't need to comment on this anyway)

**Review by brunykrijgsman — APPROVED** [review]
Overall, it looks good. However, for me, the app also broke down when I clicked pause or play. And another small comment about the parameter x for the quote() function (if I've seen it correctly) you don't use it anywhere, so it might be a bit redundant and could be removed. Other than that, I think adding the quote function is a super nice idea and adds to your package. I couldn't find the first draft of your report, so I have no feedback on that. I look forward to seeing the final product!

**Comment by catherinegua** [comment]
@jessiwitti Thank you for the great feedback! Indeed, I double checked the shiny app, and it will crash unless the library(shinyjs) is also loaded. I marked the necessary package as such shinyjs::enable, for example, but one part of the code was missing this.

I fixed this below:
`    shiny::observeEvent(input$pause, {                                                               # when the pause button is clicked, then
      shinyjs::disable("pause")                                                                                             # disable the pause button from being clicked
      values$playing <- FALSE                                                                        # pause the quotes generation
      shinyjs::enable("play")                                                                                 # allow the play button to be clicked
    })
    
    shiny::observeEvent(input$play, {                                                                # when the play button is clicked, then
      shinyjs::disable("play")                                                                                              # disable play button from being clicked
      values$playing <- TRUE                                                                         # generate a quote every 10 seconds
      shinyjs::enable("pause")                                                                                # allow pause button to be clicked
    }) `

I made a new pull request afterwards with the corrected NAMESPACE, but right now the merged one is the older version.

The report was sent to the course lecturers, as I did not know we should upload it to GitHub.

**Comment by catherinegua** [comment]
Thank you @brunykrijgsman for the feedback. Indeed, my Shiny app also requires the package "shinyjs" in order for the interface to run. I appreciate the comment about the x parameter for the quote function, as this was incorrectly updated: so good catch!

Indeed, unfortunately for the report I misunderstood and sent it to the course lecturers and not on GitHub. 

Thanks again for the comments!

**Pull request merged**
